# TODO: Make that thing work with vitest and after writting all the tests
name: Unit tests - Frontend (vitest)

on:
  push: 
    branches: 
    - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [18.12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: tests
        run: npm test
      
